### ISSUE TITLE
Unusual theme colors for brackets and parenthesis

### ISSUE THREAD

**Issue by Buco11-dev** [markusylisiurunen/github-dark-mode#159]
I just started VS like normal and noticed slight changes in the theme colors. Brackets changed to yellow, curly brackets to magenta, and parenthesis to yellow (see pics below). I don't know if this is due to an update from Github dark mode or something else. I'd like to return them to their previous states of no color. Does anyone know what is going on here?

Github dark mode before:

![image](https://user-images.githubusercontent.com/72827311/170381471-54ea030a-ff5d-405f-b80c-0dfde82cdc9a.png)

Github dark mode now:

![image](https://user-images.githubusercontent.com/72827311/170381673-51612874-8d59-455f-875c-e4737e58791f.png)

**Comment by markusylisiurunen** [comment]
Hi! I think this change is due to VS Code enabling bracket color matching by default. You can read their update here: https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

You can disable it and the colors probably will go back to how they were.

**Comment by Buco11-dev** [comment]
> Hi! I think this change is due to VS Code enabling bracket color matching by default. You can read their update here: https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default
> 
> You can disable it and the colors probably will go back to how they were.

That solved it. Thank you!
